os: linux
dist: bionic

language: java
#  - oraclejdk11

services:
  - docker  # required, but travis uses older version of docker :(

notifications:
  email: false

before_install:
  # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
  - openssl aes-256-cbc -K $encrypted_a44c20044014_key -iv $encrypted_a44c20044014_iv -in java_minitwit.enc -out /tmp/git_deploy_key -d
  # Make sure only the current user can read the private key
  - chmod 600 /tmp/git_deploy_key
  # Create a script to return the passphrase environment variable to ssh-add
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  # Start the authentication agent
  - eval "$(ssh-agent -s)"
  # Add the key to the authentication agent
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null

install:
  - docker --version  # document the version travis is using

stages:
  - docker_build
  - deploy

jobs:
  include:
    - stage: docker_build
      name: "build and push docker"
      script:
        - echo "LOGIN"
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - echo "BUILD"
        - docker build -t $DOCKER_USERNAME/java_minitwit:latest . -f Dockerfile-minitwit
        - docker build -t $DOCKER_USERNAME/minitwit_mysqlimage:latest . -f Dockerfile-mysql
        - echo "PUSH"
        - docker push $DOCKER_USERNAME/java_minitwit:latest
        - docker push $DOCKER_USERNAME/minitwit_mysqlimage:latest
        
    - stage: deploy
      name: "deploy new version"
      install: skip
      # -o flag to get around "add ip to known hosts prompt"
      script: |
        ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
        ls -a
        "source .profile && \
        cd /vagrant && \
        docker-compose pull && \
        docker-compose up -d "
